#!/usr/bin/env python3
"""0026 Step 14: fail-closed, reproducible regression and artifact evidence.

Run via verify-0026-step14.ps1 from the Diaries root. Stdlib-only so it can
still produce an honest BLOCKED report if Gradle/Docker are unavailable.
Never writes raw Docker Compose configuration or environment into evidence.
"""
import argparse
import csv
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import traceback
import xml.etree.ElementTree as ET
import zipfile

ROOT = Path(__file__).resolve().parents[3]
SCRIPTS = ROOT / 'scripts/windows/validation'
FEATURE = ROOT / 'change-control/in-progress/0026-FEAT - render ImageFragments in diaries-web'
WEB = ROOT / 'diaries-web'
RESPONDER = ROOT / 'diaries-responder'
SELECTED = ['com.rsmaxwell.diaries.web.mqtt.MqttProjectionIntegrationTest',
            'com.rsmaxwell.diaries.web.mqtt.Step12MqttHttpIntegrationTest',
            'com.rsmaxwell.diaries.web.mqtt.MqttReaderAclIntegrationTest']
SOURCE_DIRS = ['diaries-web/src', 'diaries-responder/src', 'diaries-client/src',
               'diaries-client/public', 'gradle', 'scripts/windows/validation']
SOURCE_EXACT = ['build.gradle', 'settings.gradle', 'versions.properties',
                'gradlew', 'gradlew.bat', 'diaries-web/build.gradle',
                'diaries-web/Dockerfile', 'diaries-responder/build.gradle',
                'diaries-responder/Dockerfile', 'diaries-client/package.json',
                'diaries-client/package-lock.json', 'diaries-client/angular.json',
                'diaries-client/tsconfig.json', 'diaries-client/tsconfig.app.json',
                'diaries-client/tsconfig.spec.json',
                'compose.local-docker-build.yaml', 'compose.local-published-smoke.yaml',
                'config/mosquitto/mosquitto.conf', 'config/mosquitto/aclfile.txt',
                'config/mosquitto/mosquitto-large-tree-test.conf',
                'diaries-web/config/diaries-web.docker.json']
SOURCE_EXCLUDES = {
    # Generated by diaries-client's prebuild/generate-build-info task. It contains
    # build time/identity and is intentionally ignored by the client repository.
    'diaries-client/public/assets/build-info.json',
}


def digest(path):
    h = hashlib.sha256()
    with path.open('rb') as f:
        for block in iter(lambda: f.read(1024 * 1024), b''):
            h.update(block)
    return h.hexdigest()


def manifest(root=ROOT):
    """Allow-list only; never hash credential files, local configs or DB backups."""
    paths = set()
    for directory in SOURCE_DIRS:
        base = root / directory
        if base.is_dir():
            for path in base.rglob('*'):
                if (path.is_file() and not any(part in ('build', 'node_modules', '__pycache__',
                      '.gradle', '.git', 'dist') for part in path.relative_to(root).parts)
                        and not path.name.endswith(('.pyc', '.log'))):
                    relative = path.relative_to(root).as_posix()
                    if relative not in SOURCE_EXCLUDES:
                        paths.add(relative)
    for name in SOURCE_EXACT:
        if (root / name).is_file():
            paths.add(name)
    return {name: digest(root / name) for name in sorted(paths)}


def write_manifest(path, entries):
    with path.open('w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f, lineterminator='\n')
        writer.writerow(['sha256', 'path'])
        for name, sha in entries.items():
            writer.writerow([sha, name])


def xml_results(folder):
    result = {'tests': 0, 'passed': 0, 'skipped': 0, 'failures': 0,
              'errors': 0, 'suites': [], 'skippedCases': []}
    for filename in sorted(folder.rglob('TEST-*.xml')):
        tree = ET.parse(filename).getroot()
        suites = ([tree] if tree.tag == 'testsuite' else list(tree.findall('testsuite')))
        for suite in suites:
            cases = suite.findall('.//testcase')
            for case in cases:
                result['tests'] += 1
                name = case.get('classname', suite.get('name', '')) + '#' + case.get('name', '')
                if case.find('skipped') is not None:
                    result['skipped'] += 1
                    reason = case.find('skipped').get('message', '')
                    result['skippedCases'].append({'test': name, 'reason': reason})
                elif case.find('failure') is not None:
                    result['failures'] += 1
                elif case.find('error') is not None:
                    result['errors'] += 1
                else:
                    result['passed'] += 1
            result['suites'].append(suite.get('name', filename.name))
    return result


def require_tests(summary, min_tests=1, no_skips=False, classes=()):
    if summary['tests'] < min_tests or summary['failures'] or summary['errors']:
        raise RuntimeError('Missing tests or failing XML reports: ' + json.dumps(summary))
    if no_skips and summary['skipped']:
        raise RuntimeError('Selected Docker tests were skipped: ' + json.dumps(summary['skippedCases']))
    for name in classes:
        if not any(suite == name or suite.endswith('.' + name.split('.')[-1])
                   for suite in summary['suites']):
            raise RuntimeError('Required selected integration suite missing from XML: ' + name)


def run(command, log, cwd=ROOT, env=None, print_output=True):
    """Execute without shell; stream redacted-safe, non-secret commands only."""
    with log.open('w', encoding='utf-8', errors='replace') as f:
        f.write('command: ' + ' '.join(str(arg) for arg in command) + '\n')
        f.write('cwd: ' + str(cwd) + '\n\n')
        f.flush()
        process = subprocess.Popen([str(arg) for arg in command], cwd=cwd, env=env,
                                   stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                   text=True, encoding='utf-8', errors='replace')
        for line in process.stdout:
            f.write(line)
            if print_output:
                print(line, end='', flush=True)
        code = process.wait()
        f.write('\nexit-code: %s\n' % code)
    if code:
        raise RuntimeError('%s exited %s; see %s' % (command[0], code, log))


def command_output(command, cwd=ROOT):
    try:
        return subprocess.run([str(arg) for arg in command], cwd=cwd, capture_output=True,
                              text=True, encoding='utf-8', errors='replace')
    except FileNotFoundError:
        return subprocess.CompletedProcess(command, 127, '', 'executable unavailable')


def snapshot_xml(project, destination):
    source = project / 'build/test-results/test'
    if not source.is_dir() or not list(source.glob('TEST-*.xml')):
        raise RuntimeError('No Gradle test XML at ' + str(source))
    shutil.copytree(source, destination / 'test-results')
    html = project / 'build/reports/tests/test'
    if html.is_dir():
        shutil.copytree(html, destination / 'html-reports')
    summary = xml_results(destination / 'test-results')
    (destination / 'results.json').write_text(json.dumps(summary, indent=2) + '\n', encoding='utf-8')
    return summary


def artifacts(project, prefix, dest):
    jars = sorted((project / 'build/libs').glob(prefix + '-*-fat.jar'))
    if len(jars) != 1:
        raise RuntimeError('Expected exactly one fresh %s fat JAR, got %s' % (prefix, [p.name for p in jars]))
    jar = jars[0]
    identity = {'filename': jar.name, 'sha256': digest(jar), 'sizeBytes': jar.stat().st_size}
    with zipfile.ZipFile(jar) as f:
        for info in f.infolist():
            if info.filename.endswith('build-info.properties') and not info.is_dir():
                text = f.read(info).decode('utf-8', errors='replace')
                identity['embeddedBuildInfo'] = {line.split('=', 1)[0]: line.split('=', 1)[1]
                     for line in text.splitlines() if '=' in line and not line.startswith('#')}
                break
    dest.write_text(json.dumps(identity, indent=2) + '\n', encoding='utf-8')
    return identity


def compose_check(docker, compose, envfile, destination, inspect_images=False):
    """Parse Compose JSON in memory; NEVER persist full rendered config/secrets."""
    command = [docker, 'compose']
    if envfile:
        command += ['--env-file', str(envfile)]
    command += ['-f', str(compose), 'config', '--format', 'json']
    proc = command_output(command)
    if proc.returncode:
        # Docker error text can echo user input; report only its category.
        raise RuntimeError('Compose render failed for %s (exit %s). Inspect env file/variables locally; raw output intentionally omitted.'
                           % (compose.name, proc.returncode))
    raw = json.loads(proc.stdout)
    result = {'composeFile': compose.name, 'environmentSource': str(envfile) if envfile else 'process environment',
              'rendered': True, 'services': {}, 'volumes': sorted(raw.get('volumes', {}).keys()),
              'containersStarted': False}
    for name, definition in sorted(raw.get('services', {}).items()):
        entry = {'image': definition.get('image'), 'hasBuild': bool(definition.get('build')),
                 'healthcheck': 'present' if definition.get('healthcheck') else 'absent',
                 'dependsOn': sorted(definition.get('depends_on', {}).keys())}
        if inspect_images and entry['image'] and not entry['hasBuild']:
            inspect = command_output([docker, 'image', 'inspect', entry['image'], '--format', '{{json .}}'])
            if inspect.returncode:
                # Published-image inspection is opportunistic at Step 14. The exact
                # deployed/published reader artifact is a Step 15 acceptance gate.
                # Do not pull or manufacture an image here; record local absence.
                entry['imageInspection'] = {'availableLocally': False}
            else:
                obj = json.loads(inspect.stdout)
                entry['imageInspection'] = {'availableLocally': True, 'id': obj['Id'],
                                            'repoDigests': obj.get('RepoDigests', []),
                                            'created': obj.get('Created')}
        result['services'][name] = entry
    destination.write_text(json.dumps(result, indent=2) + '\n', encoding='utf-8')
    return result


def git_identities():
    result = {}
    for label, location in [('diaries', ROOT), ('diaries-responder', RESPONDER),
                            ('diaries-web', WEB), ('diaries-client', ROOT / 'diaries-client')]:
        head = command_output(['git', 'rev-parse', 'HEAD'], cwd=location)
        status = command_output(['git', 'status', '--porcelain'], cwd=location)
        result[label] = ({'head': head.stdout.strip(),
                          'workingTreeEntries': len(status.stdout.splitlines())}
                         if head.returncode == 0 and status.returncode == 0 else 'GIT_METADATA_UNAVAILABLE')
    return result


def hashes(evidence):
    with (evidence / 'SHA256SUMS.txt').open('w', encoding='utf-8', newline='\n') as f:
        for path in sorted(p for p in evidence.rglob('*') if p.is_file() and p.name != 'SHA256SUMS.txt'):
            f.write('%s  %s\n' % (digest(path), path.relative_to(evidence).as_posix()))



def validate_evidence_location(evidence, forbidden=None):
    """Reject evidence paths that a verification build may delete."""
    evidence = evidence.resolve()
    forbidden = forbidden or [WEB / 'build', RESPONDER / 'build', ROOT / 'diaries-client' / 'dist']
    for output in forbidden:
        output = Path(output).resolve()
        if evidence == output or output in evidence.parents:
            raise ValueError(
                'Evidence directory must not be inside generated output that Step 14 cleans/builds: '
                + str(output) + '. Use a safe location such as ' + str(ROOT / 'build' / 'step14-YYYYMMDD-HHMMSS'))
    return evidence

def run_verification(args):
    evidence = validate_evidence_location(args.evidence)
    if evidence.exists():
        raise ValueError('Evidence directory must be new, so old reports cannot be mistaken for this run: ' + str(evidence))
    evidence.mkdir(parents=True)
    results = {'step': 14, 'status': 'BLOCKED', 'startedUtc': dt.datetime.now(dt.timezone.utc).isoformat(),
               'source': str(ROOT), 'checks': {}, 'omissions': [], 'failures': []}
    before = manifest()
    (evidence / 'git-identity.json').write_text(json.dumps(git_identities(), indent=2) + '\n', encoding='utf-8')
    write_manifest(evidence / 'source-sha256-before.csv', before)
    gradle = ROOT / ('gradlew.bat' if os.name == 'nt' else 'gradlew')
    try:
        prerequisites = {}
        for cmd in ('java', 'node', 'docker'):
            proc = command_output([cmd, '-version' if cmd == 'java' else '--version'])
            prerequisites[cmd] = (proc.stderr or proc.stdout).strip().splitlines()[:3] if proc.returncode == 0 else 'NOT_AVAILABLE'
        info = command_output(['docker', 'info', '--format', '{{.ServerVersion}}'])
        prerequisites['dockerDaemon'] = info.stdout.strip() if info.returncode == 0 else 'NOT_AVAILABLE'
        (evidence / 'prerequisites.json').write_text(json.dumps(prerequisites, indent=2) + '\n', encoding='utf-8')
        if args.preflight_only:
            results['omissions'].append('Preflight-only: all regression/build/Compose/browser gates NOT RUN')
            return results
        if prerequisites['dockerDaemon'] == 'NOT_AVAILABLE':
            raise RuntimeError('Docker engine unavailable: real-MQTT/Testcontainers tests are mandatory; no skip accepted.')
        if prerequisites['java'] == 'NOT_AVAILABLE':
            raise RuntimeError('Java/Gradle unavailable; JDK 25 toolchain is required.')
        for filename in ['step13-retained-snapshot.test.cjs', 'step13-image-http.test.cjs', 'step13-proxy-routing.test.cjs']:
            run(['node', '--test', str(SCRIPTS / filename)], evidence / (filename + '.log'))
        results['checks']['step13HarnessRegressions'] = 'PASSED'

        run([gradle, ':diaries-web:clean', ':diaries-web:test', ':diaries-web:build',
             '--rerun-tasks', '--console=plain'], evidence / 'web-full-test-build.log')
        folder = evidence / 'web-ordinary'
        folder.mkdir()
        report = snapshot_xml(WEB, folder)
        require_tests(report)
        results['checks']['webFullSuiteAndBuild'] = report

        selected = [str(gradle), ':diaries-web:test']
        for klass in SELECTED:
            selected += ['--tests', klass]
        selected += ['--rerun-tasks', '--console=plain']
        run(selected, evidence / 'web-real-mqtt-selected.log')
        folder = evidence / 'web-real-mqtt'
        folder.mkdir()
        selected_report = snapshot_xml(WEB, folder)
        require_tests(selected_report, no_skips=True, classes=SELECTED)
        results['checks']['webRealMqtt'] = selected_report

        # Tests regenerate embedded build-info resources: seal the final JAR after tests.
        run([gradle, ':diaries-web:shadowJar', '--rerun-tasks', '--console=plain'],
            evidence / 'web-final-jar-build.log')
        results['checks']['webArtifact'] = artifacts(WEB, 'diaries-web', evidence / 'web-artifact.json')

        if args.full_responder:
            run([gradle, ':diaries-responder:clean', ':diaries-responder:test',
                 ':diaries-responder:build', '--rerun-tasks', '--console=plain'],
                evidence / 'responder-full-test-build.log')
            folder = evidence / 'responder-ordinary'
            folder.mkdir()
            responder_report = snapshot_xml(RESPONDER, folder)
            require_tests(responder_report)
            results['checks']['responderFullSuiteAndBuild'] = responder_report
            results['checks']['responderArtifact'] = artifacts(RESPONDER, 'diaries-responder',
                                                                evidence / 'responder-artifact.json')
        else:
            results['omissions'].append('Responder suite not rerun: pass --full-responder if its source/contracts changed; see 0025 Step 14 evidence')

        if args.client:
            if not (ROOT / 'diaries-client/node_modules').is_dir():
                raise RuntimeError('Client node_modules missing: npm ci in diaries-client first.')
            run(['npm.cmd' if os.name == 'nt' else 'npm', 'test', '--', '--watch=false',
                 '--browsers=ChromeHeadless'], evidence / 'client-tests.log', cwd=ROOT / 'diaries-client')
            run(['npm.cmd' if os.name == 'nt' else 'npm', 'run', 'build', '--', '--configuration',
                 'production'], evidence / 'client-production-build.log', cwd=ROOT / 'diaries-client')
            results['checks']['clientSuiteAndProductionBuild'] = 'PASSED (see client logs)'
        else:
            results['omissions'].append('Client tests/build not rerun: pass --client if client source changed')

        for label, name, env_file in [('local-build', 'compose.local-docker-build.yaml', args.build_env),
                                       ('published-smoke', 'compose.local-published-smoke.yaml', args.published_env)]:
            summary = compose_check('docker', ROOT / name, env_file,
                                    evidence / ('compose-' + label + '.json'),
                                    inspect_images=(label == 'published-smoke' and args.inspect_published))
            results['checks']['compose-' + label] = summary
        if not args.inspect_published:
            results['omissions'].append('Published image IDs/digests NOT INSPECTED; --inspect-published checks locally pulled images')
        if args.backup:
            step13 = evidence / 'step13-fresh'
            script = SCRIPTS / 'verify-0026-step13.ps1'
            if os.name != 'nt':
                raise RuntimeError('Step 13 wrapper requires PowerShell 7 on Windows')
            run(['pwsh', '-NoProfile', '-File', str(script), '-BackupFile', str(args.backup),
                 '-EvidenceDirectory', str(step13)], evidence / 'step13-fresh.log')
            summary_path = step13 / 'evidence/summary.json'
            summary = json.loads(summary_path.read_text(encoding='utf-8'))
            if summary.get('status') != 'PASSED' or summary.get('cleanupFailures') or any(
                    summary.get(k) is not False for k in ('liveDevelopmentDatabaseModified',
                    'productionDatabaseModified', 'liveNasModified')):
                raise RuntimeError('Step 13 did not pass its safety gates')
            candidate_file = step13 / 'evidence/candidate-artifacts.json'
            candidates = json.loads(candidate_file.read_text(encoding='utf-8'))
            final_web = artifacts(WEB, 'diaries-web', evidence / 'web-final-candidate-after-browser.json')
            final_responder = artifacts(RESPONDER, 'diaries-responder',
                                        evidence / 'responder-final-candidate-after-browser.json')
            if final_web['sha256'] != candidates['web']['sha256'] or final_responder['sha256'] != candidates['responder']['sha256']:
                raise RuntimeError('Fresh browser JAR hashes do not match the final local built release candidate')
            results['checks']['freshBrowserAndCrossComponent'] = {
                'status': 'PASSED', 'summarySha256': digest(summary_path),
                'candidateArtifactSha256': digest(candidate_file),
                'finalCandidateWebJarSha256': final_web['sha256'],
                'finalCandidateResponderJarSha256': final_responder['sha256']}
        else:
            results['omissions'].append('Fresh browser/cross-component run NOT performed; supply --backup to rerun disposable Step 13 for exact-source candidate')
        results['status'] = 'PASSED_WITH_OMISSIONS' if results['omissions'] else 'PASSED'
    except BaseException as err:
        results['failures'].append(str(err))
        results['status'] = 'BLOCKED'
        (evidence / 'exception.txt').write_text(traceback.format_exc(), encoding='utf-8')
    finally:
        after = manifest()
        write_manifest(evidence / 'source-sha256.csv', after)
        removed, added, changed = (sorted(before.keys() - after.keys()),
                                   sorted(after.keys() - before.keys()),
                                   sorted(k for k in before.keys() & after.keys() if before[k] != after[k]))
        results['sourceInventory'] = {'files': len(before), 'stable': not (removed or added or changed),
                                      'removed': removed, 'added': added, 'changed': changed}
        if removed or added or changed:
            results['status'] = 'BLOCKED'
            results['failures'].append('Source changed during verification: rerun complete Step 14 against exact final source')
        results['finishedUtc'] = dt.datetime.now(dt.timezone.utc).isoformat()
        (evidence / 'RESULTS.json').write_text(json.dumps(results, indent=2) + '\n', encoding='utf-8')
        hashes(evidence)
    return results


def cli():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--evidence', required=True, type=Path)
    parser.add_argument('--preflight-only', action='store_true')
    parser.add_argument('--full-responder', action='store_true')
    parser.add_argument('--client', action='store_true')
    parser.add_argument('--backup', type=Path, help='Rerun disposable Step 13 browser fixture')
    parser.add_argument('--build-env', type=Path, help='Real local-docker-build Compose environment file')
    parser.add_argument('--published-env', type=Path, help='Real published-smoke Compose environment file')
    parser.add_argument('--inspect-published', action='store_true')
    args = parser.parse_args()
    if args.backup and not args.backup.is_file():
        parser.error('--backup file is missing')
    for label in ('build_env', 'published_env'):
        value = getattr(args, label)
        if value and not value.is_file():
            parser.error('--%s file is missing' % label.replace('_', '-'))
    result = run_verification(args)
    print('\nStep 14: %s; evidence: %s' % (result['status'], args.evidence))
    if result['failures']:
        print('Failure: ' + '; '.join(result['failures']))
    if result['omissions']:
        print('Outstanding: ' + '; '.join(result['omissions']))
    return 0 if result['status'] == 'PASSED' else 1


if __name__ == '__main__':
    sys.exit(cli())
