-- Included by 002 only, after absence and privilege checks.
CREATE TABLE public.image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT image_pkey PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0 CONSTRAINT image_version_check CHECK (version >= 0),
    relative_path TEXT NOT NULL,
    mime_type VARCHAR(127) NOT NULL CONSTRAINT image_mime_type_check
        CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/gif', 'image/webp')),
    original_filename TEXT NOT NULL,
    width INTEGER NOT NULL CONSTRAINT image_width_check CHECK (width > 0),
    height INTEGER NOT NULL CONSTRAINT image_height_check CHECK (height > 0),
    checksum CHAR(64) NOT NULL CONSTRAINT image_checksum_check
        CHECK (checksum ~ '^[0-9a-f]{64}$'),
    caption TEXT NOT NULL DEFAULT '',
    alt_text TEXT NOT NULL DEFAULT ''
);
-- PostgreSQL 18's deterministic Unicode collation avoids OS/DB locale-dependent
-- case identity. Phase 3 lookups must use this exact expression on NFC paths.
CREATE UNIQUE INDEX image_relative_path_ci_uq
    ON public.image (lower(relative_path COLLATE pg_catalog.pg_unicode_fast));
CREATE INDEX image_checksum_idx ON public.image (checksum);
